# Generated by Django 5.2.7 on 2026-02-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('unread', '未読'), ('read_later', '後で読む'), ('read', '読了'), ('reread', '要再読'), ('hof', '殿堂入り'), ('archived', 'アーカイブ')], default='unread', max_length=10),
        ),
    ]
