# Generated by Django 5.2.7 on 2026-03-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rss_subscription_and_article_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedurl',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cachedurl',
            name='fetch_status',
            field=models.CharField(choices=[('pending', '未取得'), ('success', '取得成功'), ('failed', '取得失敗'), ('not_found', '404/410')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cachedurl',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedurl',
            name='last_http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedurl',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
