# Generated by Django 5.2.7 on 2026-02-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedurl',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
