# Generated by Django 5.2.7 on 2025-10-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='repetition_level',
            field=models.IntegerField(default=0),
        ),
    ]
