# Generated by Django 5.2.7 on 2026-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_cachedurl_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='classification_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='classification_status',
            field=models.CharField(choices=[('pending', '未処理'), ('processing', '処理中'), ('completed', '完了'), ('error', 'エラー')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='suggested_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='suggested_category_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='suggested_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
