"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# .env ファイルから環境変数を読み込む
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 開発環境ではCeleryタスクを同期実行（ワーカーなしで動作）
if DEBUG:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

# ★AI分類エンジン設定
# 'lightweight' = キーワードマッチング版（軽量、高速）
# 'transformers' = HuggingFace transformers 版（精度重視、GPU推奨）
AI_CLASSIFICATION_ENGINE = os.getenv('AI_CLASSIFICATION_ENGINE', 'lightweight')

# ★AI カテゴリ候補（SBERT 版で使用）
AI_CATEGORY_CANDIDATES = [
    "プログラミング",
    "AI・機械学習",
    "インフラ・クラウド",
    "フロントエンド",
    "データサイエンス",
    "セキュリティ",
    "ビジネス・キャリア",
    "経済・金融",
    "政治",
    "社会",
    "国際",
    "科学",
    "健康・医療",
    "スポーツ",
    "エンタメ",
    "文化・アート",
    "生活・暮らし",
    "教育",
    "交通・モビリティ",
    "環境・気候",
    "ガジェット",
    "テクノロジー",
    "ニュース・時事",
    "その他・ポエム"
]

ALLOWED_HOSTS = [
    '10.0.2.2',      # ★ Androidエミュレータからのアクセスを許可
    '127.0.0.1',   # 既存のlocalhost
    'localhost',     #
]

# CSRF設定
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',  # ★この行を一番上に追加
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 追加したライブラリ
    'rest_framework',
    'rest_framework_simplejwt',
    
    # 追加したアプリ
    'articles',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ★この行を追加
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
        # ★テストログイン用にこの行を追加
        'rest_framework.authentication.SessionAuthentication', 
    ),
    # ... (以下はそのまま)
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',  # ソート機能を追加
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,  # 無限スクロール用に1ページ12件（3カラム × 4行）
}

# ========== CELERY SETTINGS ==========
# タスク（処理の依頼）を保存する場所 (ブローカー) としてRedisを指定
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# タスクの結果を保存する場所 (バックエンド) としてRedisを指定
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tokyo' # タイムゾーンを日本に設定

# ========== CORS SETTINGS ==========

# True にすると、すべてのドメインからのアクセスを許可 (開発中は便利)
CORS_ALLOW_ALL_ORIGINS = True

# (もし本番環境などでドメインを制限したい場合は、以下のように設定します)
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",      # 開発中のReactアプリなど
#     "http://127.0.0.1:3000",      #
#     "https://your-app-domain.com", # 本番のドメイン
# ]

# 許可するHTTPヘッダー (Authorization ヘッダーを許可)
CORS_ALLOW_HEADERS = [
    'accept',
    'authorization', # ★JWT認証のために必須
    'content-type',
    'origin',
    'x-csrftoken',
    'x-requested-with',
]


# ========== LOGIN SETTINGS ==========
LOGIN_URL = '/accounts/login/' # ログイン画面の場所（ここを変更！）

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# 1. どのドメインからのアクセスも許可する
ALLOWED_HOSTS = ['*'] 
# ※本番では '*' ではなく具体的なドメインを指定しますが、開発中はこれでOKです

# 2. ★重要：ngrok経由でのフォーム送信（CSRF）を許可する
# これがないと「保存ボタン」を押したときにエラーになります
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',  # ★これを追加！
]